Repository busyorg/busy, pull requests merged in 2018-05, with the labels that each got.

#1816 chore: migrate from pre-commit to husky
  package.json
  yarn.lock
Labels: Greenkeeper

#1817 chore: replace visualizer with bundle analyzer
  package.json
  webpack/makeConfig.js
  yarn.lock
Labels: Greenkeeper

#1664 Add Trending Tags Slider to mobile home feeds
  src/client/components/TopicSelector.less
  src/client/components/TrendingTagsMenu.js
  src/client/components/TrendingTagsMenu.less
  src/client/feed/Page.js
  src/client/locales/default.json
Labels: Needs design

#1815 chore: update to less 3
  package.json
  src/client/styles/common.less
  src/client/styles/fonts.less
  src/client/styles/modules/drafts-layout.less
  src/client/styles/modules/feed-layout.less
  src/client/styles/modules/menu-layout.less
  src/client/styles/modules/post-layout.less
  src/client/styles/modules/settings-layout.less
  src/client/styles/modules/topnav-layout.less
  webpack/makeConfig.js
  webpack/webpack-dev-server.js
  yarn.lock
Labels: Greenkeeper

#1821 refactor: clean up webpack and legacy code
  .babelrc
  .eslintignore
  .eslintrc.js
  package.json
  src/client/index.js
  src/client/post/Post.js
  src/client/reducers.js
  src/client/store.js
  src/client/vendor/responsive.js
  src/client/vendor/responsive/redux-mediaquery.js
  webpack/configUtils.js
  webpack/index.js
  webpack/makeConfig.js
  webpack/webpack-dev-server.js
  webpack/webpack.config.js
  webpack/webpack.dev.config.js
  webpack/webpack.prod.config.js
  webpack/webpack.server.config.js
  yarn.lock
Labels: Greenkeeper, Refactor

#1814 refactor: improve localization system
  src/client/Wrapper.js
  src/client/app/appReducer.js
  src/client/components/Navigation/LanguageSettings.js
  src/client/index.js
  src/client/reducers.js
  src/client/settings/Settings.js
  src/client/translations/index.js
  src/client/translations/languages.js
Labels: Refactor

#1823 refactor: make reducers and busyAPI module pure
  src/client/Wrapper.js
  src/client/app/appActions.js
  src/client/auth/authActions.js
  src/client/busyAPI.js
  src/client/reducers.js
  src/client/store.js
  src/client/user/userActions.js
  src/common/services/createBusyAPI.js
Labels: Refactor

#1830 chore: remove unused helper
  src/client/helpers/languages.js
Labels: Greenkeeper

#1832 chore: remove react-test-renderer
  package.json
  yarn.lock
Labels: Greenkeeper

#1833 refactor: remove transitions from ReduxInfiniteScroll
  package.json
  src/client/vendor/ReduxInfiniteScroll.js
  src/client/wallet/__tests__/__snapshots__/UserWalletTransactions.test.js.snap
  yarn.lock
Labels: Code quality

#1755 Add back to the top button
  src/client/Wrapper.js
  src/client/components/BBackTop.js
  src/client/components/BBackTop.less
  src/client/post/PostModal.js
  src/client/styles/fonts.less
Labels: PR: WIP

#1831 chore: remove Block user menu
  src/client/components/UserHeader.js
  src/client/components/UserHeader.less
  src/client/user/User.js
  src/client/user/UserHero.js
Labels: bug

#1863 fix: add missing contenthash to CSS
  webpack/client.js
Labels: bug

#1865 refactor: update prop types
  src/client/components/Popover.js
  src/client/components/PopoverMenu/PopoverMenu.js
  src/client/components/PopoverMenu/PopoverMenuItem.js
  src/client/components/UserCard.js
  src/client/vendor/ReduxInfiniteScroll.js
Labels: code quality

#1873 Add parentheses for calculations of comment width offset
  src/client/components/Comments/Comment.less
Labels: bug

#1835 Show powered-up username on power up transaction
  src/client/locales/en.json
  src/client/wallet/PowerUpTransaction.js
  src/client/wallet/WalletTransaction.js
  src/client/wallet/__tests__/PowerUpTransaction.test.js
  src/client/wallet/__tests__/__snapshots__/PowerUpTransaction.test.js.snap
Labels: PR: needs update
