Repository busyorg/busy, pull requests merged in 2018-04, with the labels that each got.

#1700 fix: set header width to 100vw
  src/client/Wrapper.js
  src/client/styles/common.less
Labels: Bug

#1701 Update Claim Rewards button to have primary action button styles
  src/client/wallet/ClaimRewardsBlock.js
Labels: Style

#1696 Forward to shortest link possible after creating post
  src/client/post/Write/editorActions.js
Labels: Bug

#1689 Prevent overflow on user info on profile page
  src/client/components/Sidebar/User.less
Labels: Bug

#1709 Add post with DMCA notice
  src/common/constants/dmca.json
Labels: DMCA

#1707 Fix for drafts not saving correctly
  src/client/post/Write/Write.js
Labels: Bug

#1697 filter object as tag edge case
  src/client/components/Story/StoryFull.js
Labels: Bug

#1790 Update check for last action count
  src/client/wallet/walletReducer.js
Labels: Bug

#1794 fix: remove pointer cursor from comments h2
  src/client/components/Story/StoryFull.less
Labels: Bug
