Repository busyorg/busy, pull requests merged in 2018-02, with the labels that each got.

#1496 Simplify CSS
  assets/images/banner.png
  src/client/activity/UserActivitySearch.less
  src/client/components/Button/Action.less
  src/client/components/Button/Follow.less
  src/client/components/CommentFooter/CommentFooter.less
  src/client/components/CommentFooter/Confirmation.less
  src/client/components/Comments/Comment.less
  src/client/components/Comments/CommentForm.less
  src/client/components/Comments/EmbeddedCommentForm.less
  src/client/components/Editor/EditorInput.less
  src/client/components/Hero.less
  src/client/components/Icon/Loading.less
  src/client/components/LoginModal.less
  src/client/components/Navigation/Sidenav.less
  src/client/components/Navigation/Topnav.less
  src/client/components/PopoverMenu/PopoverMenuItem.less
  src/client/components/QuickPostEditor/QuickPostEditor.less
  src/client/components/Sidebar/CryptoChart.js
  src/client/components/Sidebar/CryptoTrendingCharts.js
  src/client/components/Sidebar/CryptoTrendingCharts.less
  src/client/components/Sidebar/LatestComments.less
  src/client/components/Sidebar/PostRecommendation.less
  src/client/components/Sidebar/SidebarBlock.less
  src/client/components/Story/StoryFull.less
  src/client/components/StoryFooter/Buttons.less
  src/client/components/StoryFooter/Confirmation.less
  src/client/components/UserHeader.less
  src/client/components/UserMenu.less
  src/client/invite/Invite.less
  src/client/styles/custom.less
  src/client/wallet/UserWalletSummary.less
Labels: Refactor

#1417 Add LetsGetStarted Sidebar Block
  src/client/activity/UserActivityActions.less
  src/client/app/Sidebar/RightSidebar.js
  src/client/components/HorizontalBarChart.js
  src/client/components/HorizontalBarChart.less
  src/client/components/QuickPostEditor/QuickPostEditor.less
  src/client/components/Sidebar/SidebarContentBlock.less
  src/client/feed/LetsGetStarted.js
  src/client/feed/LetsGetStarted.less
  src/client/feed/LetsGetStartedIcon.js
  src/client/feed/SubFeed.js
  src/client/locales/default.json
  src/client/locales/en-US.json
  src/client/reducers.js
  src/client/styles/custom.less
  src/client/styles/mixins.less
  src/client/user/userReducer.js
Labels: Feature

#1513 Fix signup link
  .env.example
  assets/service-worker.js
  config.json
  package.json
  src/client/components/Hero.js
  src/client/components/HeroBanner.js
  src/client/components/LoginModal.js
  src/client/components/Navigation/Topnav.js
  src/client/components/Sidebar/SignUp.js
  src/client/helpers/pushpadHelper.js
  webpack/makeConfig.js
  webpack/webpack-dev-server.js
  webpack/webpack.server.config.js
Labels: Bug

#1376 Add PostModal component & integrate it with Feed
  src/client/app/appActions.js
  src/client/app/appReducer.js
  src/client/components/Story/Story.js
  src/client/feed/Feed.js
  src/client/feed/SubFeed.js
  src/client/locales/default.json
  src/client/post/PostModal.js
  src/client/post/PostModal.less
  src/client/post/PostModalContainer.js
  src/client/reducers.js
  src/client/styles/common.less
  src/client/styles/custom.less
  src/client/styles/fonts.less
  src/client/user/UserProfile.js
Labels: Feature

#1518 Check if feed is empty for EmptyFeed
  src/client/feed/SubFeed.js
Labels: Bug

#1516 Configure scripts
  .editorconfig
  .prettierignore
  .prettierrc.js
  scripts/prettier/index.js
Labels: Refactor

#1506 Refactor Feed
  src/client/bookmarks/Bookmarks.js
  src/client/components/Story/Story.js
  src/client/feed/Feed.js
  src/client/feed/StoryContainer.js
  src/client/feed/SubFeed.js
  src/client/feed/feedActions.js
  src/client/helpers/stateHelpers.js
  src/client/replies/Replies.js
  src/client/user/UserComments.js
  src/client/user/UserFeed.js
  src/client/user/UserProfile.js
  src/client/user/UserReblogs.js
Labels: Refactor

#1522 PostModal Updates
  src/client/components/Story/Story.js
  src/client/components/Story/StoryFull.js
  src/client/post/PostModal.js
  src/client/post/PostModalContainer.js
Labels: Bug

#1526 fix(client): update locale check in charts
  src/client/helpers/cryptosHelper.js
Labels: Bug

#1482 Access settings to see if should upvote on quickpost
  src/client/components/QuickPostEditor/QuickPostEditor.js
Labels: Feature

#1536 Add ability to ctrl/cmd click and open new tab to post
  src/client/components/Story/Story.js
Labels: Bug

#1534 Fix for NSFW posts preview
  src/client/components/Story/Story.js
Labels: Bug

#1535 Update styles for quote block in post body
  src/client/components/Story/Body.less
Labels: Style

#1488 Update search placeholder & styles
  src/client/activity/UserActivityActions.less
  src/client/components/Avatar.less
  src/client/components/Navigation/Topnav.js
  src/client/components/Navigation/Topnav.less
  src/client/components/QuickPostEditor/QuickPostEditor.less
  src/client/components/Sidebar/LatestComments.less
  src/client/components/Sidebar/PostRecommendation.less
  src/client/components/Story/Body.less
  src/client/components/Story/Story.less
  src/client/components/Story/StoryFull.less
  src/client/components/Story/StoryLoading.less
  src/client/components/UserCard.less
  src/client/discover/Discover.less
  src/client/invite/Invite.less
  src/client/locales/default.json
  src/client/post/PostModal.less
  src/client/post/Write/DraftRow.less
  src/client/search/Search.less
  src/client/styles/custom.less
  src/client/styles/modules/popover-layout.less
  src/client/user/UserDynamicList.less
  src/client/wallet/ClaimRewardsBlock.less
  src/client/wallet/UserWalletSummary.less
  src/client/wallet/UserWalletTransactions.less
Labels: Style

#1519 Use reload action after claiming rewards
  src/client/auth/authActions.js
  src/client/auth/authReducer.js
  src/client/wallet/ClaimRewardsBlock.js
Labels: Bug

#1548 Fix for User Comments not opening
  src/client/components/Story/Story.js
  src/client/feed/Feed.js
Labels: Bug

#1544 Add Notifications on Client Side
  package.json
  src/client/Wrapper.js
  src/client/auth/__tests__/authReducers.js
  src/client/auth/authActions.js
  src/client/auth/authReducer.js
  src/client/busyAPI.js
  src/client/components/Navigation/Notifications/Notification.less
  src/client/components/Navigation/Notifications/NotificationFollowing.js
  src/client/components/Navigation/Notifications/NotificationMention.js
  src/client/components/Navigation/Notifications/NotificationReply.js
  src/client/components/Navigation/Notifications/Notifications.js
  src/client/components/Navigation/Notifications/Notifications.less
  src/client/components/Navigation/Topnav.js
  src/client/components/Navigation/Topnav.less
  src/client/helpers/formatter.js
  src/client/helpers/metadata.js
  src/client/locales/default.json
  src/client/locales/en-US.json
  src/client/notifications/Notifications.js
  src/client/notifications/Notifications.less
  src/client/reducers.js
  src/client/styles/common.less
  src/client/styles/custom.less
  src/client/styles/fonts.less
  src/client/user/userActions.js
  src/client/user/userReducer.js
  src/common/constants/notifications.js
  src/common/routes.js
  yarn.lock
Labels: Feature

#1556 Fix for Follower/Following List Count
  src/client/user/UserDynamicList.js
Labels: Bug

#1542 Remove unneeded history push
  src/client/post/Post.js
  src/client/post/PostModal.js
Labels: Bug

#1479 Add scrollbars to tags and update scrollbars styles
  src/client/components/Story/StoryFull.js
  src/client/components/Story/StoryFull.less
  src/client/components/UserMenu.js
Labels: Style

#1537 Update editor styles
  src/client/components/Editor/EditorInput.less
  src/client/components/Editor/EditorToolbar.js
  src/client/components/Editor/EditorToolbar.less
Labels: Style
