Repository busyorg/busy, pull requests merged in 2018-03, with the labels that each got.

#1595 Add PostModal to bookmarks page
  src/client/bookmarks/Bookmarks.js
Labels: Bug

#1599 Remove Sentry and NewRelic
  app.json
  package.json
  src/client/index.js
  src/server/app.js
  src/server/handlers/createSsrHandler.js
  src/server/index.js
  webpack/makeConfig.js
  webpack/webpack-dev-server.js
  webpack/webpack.server.config.js
  yarn.lock
Labels: Refactor

#1602 Handle both old and new API cases for top reblogged users
  src/client/activity/UserActionIcon.js
  src/client/components/Sidebar/InterestingPeopleWithAPI.js
Labels: Feature

#1604 allow curation rewards for comments
  src/client/comments/commentsActions.js
Labels: Bug

#1622 Fix for SSR error - window undefined
  src/client/components/Navigation/Topnav.js
Labels: Bug

#1626 fix: handle timeout on AMP
  src/server/handlers/createAmpHandler.js
Labels: Bug

#1628 refactor: remove html5shiv
  templates/index.html
  templates/production_index.html
Labels: Refactor

#1631 Update Busy link regex
  src/client/vendor/SanitizeConfig.js
Labels: Bug

#1636 Login user with busy api
  src/client/Wrapper.js
  src/client/auth/authActions.js
Labels: Feature

#1646 Update post table background
  src/client/components/Story/Body.less
  src/client/styles/custom.less
Labels: Style

#1627 refactor(ssr): use async/await on the server
  src/server/app.js
  src/server/auth-server.js
  src/server/handlers/createAmpHandler.js
  src/server/handlers/createSsrHandler.js
Labels: Refactor

#1644 Subscribe to Notifications & Add Notification Popup
  package.json
  src/client/Wrapper.js
  src/client/app/appActions.js
  src/client/components/Editor/Editor.js
  src/client/components/Editor/Editor.less
  src/client/components/Editor/EditorInput.js
  src/client/components/Navigation/Notifications/Notification.less
  src/client/components/Navigation/Notifications/Notifications.js
  src/client/components/Navigation/Notifications/Notifications.less
  src/client/components/QuickPostEditor/QuickPostEditor.js
  src/client/helpers/notificationsHelper.js
  src/client/locales/default.json
  src/client/notifications/NotificationPopup.js
  src/client/notifications/NotificationPopup.less
  src/client/reducers.js
  src/client/styles/common.less
  src/client/styles/custom.less
  src/client/user/userReducer.js
  src/common/constants/notifications.js
  yarn.lock
Labels: Feature

#1654 feat: migrate to busy-ipfs
  src/client/components/Editor/withEditor.js
  src/client/helpers/image.js
Labels: Feature, Refactor

#1655 Fix for comment input erasing on error
  src/client/components/Comments/Comment.js
  src/client/components/Comments/CommentForm.js
  src/client/components/Comments/Comments.js
Labels: Bug

#1657 Fix for edit profile form not filling
  src/client/settings/ProfileSettings.js
Labels: Bug

#1663 Add dmca.json and check if post contains a banned author or id
  src/client/components/Story/DMCARemovedMessage.js
  src/client/components/Story/Story.js
  src/client/helpers/postHelpers.js
  src/client/locales/default.json
  src/client/post/Post.js
  src/client/post/PostContent.js
  src/client/post/PostModal.js
  src/common/constants/dmca.json
Labels: High priority

#1649 Fix for mobile browsers being able to move post modal
  src/client/Wrapper.js
  src/client/post/PostModal.less
Labels: Bug

#1661 Fix for mobile search causing blank screen
  src/client/components/Navigation/Topnav.js
Labels: Bug

#1669 Fix for editor preview not working after tags error
  src/client/components/Editor/Editor.js
Labels: Bug

#1659 Update antd popup messages z-index
  src/client/styles/common.less
  src/client/styles/custom.less
Labels: Bug, Style

#1673 Fix bug on pages where posted from would fail
  src/client/helpers/postHelpers.js
Labels: Bug

#1671 Add Translations to topics validator in Editor component
  src/client/components/Editor/Editor.js
Labels: Bug

#1670 Use current users upvote setting when creating a post
  src/client/post/Write/Write.js
Labels: Bug

#1688 fix: prevent replacement patterns
  src/server/renderers/ssrRenderer.js
Labels: Bug
