Repository busyorg/busy, pull requests merged in 2018-06, with the labels that each got.

#1927 Fix the unwanted side padding
  src/client/styles/modules/feed-layout.less
Labels: bug

#1926 Display custom errors instead of Unkown error
  src/client/errorMiddleware.js
  src/common/constants/errors.js
Labels: bug

#1987 Add post into DMCA list
  src/common/constants/dmca.json
Labels: DMCA

#1965 Add exit page option to settings page + whitelist domains
  src/client/components/Comments/Comment.js
  src/client/components/Comments/CommentForm.js
  src/client/components/Comments/EmbeddedCommentForm.js
  src/client/components/Editor/Editor.js
  src/client/components/Story/Body.js
  src/client/components/Story/StoryFull.js
  src/client/containers/Story/BodyContainer.js
  src/client/discover/DiscoverContent.js
  src/client/helpers/constants.js
  src/client/helpers/regexHelpers.js
  src/client/locales/default.json
  src/client/reducers.js
  src/client/settings/ProfileSettings.js
  src/client/settings/Settings.js
  src/client/settings/__tests__/settingsReducer.js
  src/client/settings/settingsReducer.js
  src/client/user/userReducer.js
  src/client/vendor/SanitizeConfig.js
Labels: feature

#1989 fix: add z-index to BBackTop
  src/client/components/BBackTop.less
  src/client/styles/custom.less
Labels: PR: needs update
